# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: API CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install SwaggerHub cli  
        run: npm install swaggerhub-cli -g && npm install js-yaml
        
      - name: Install jq utility
        run: sudo apt-get --yes --quiet install jq

# get the ORG, API and VER from the branch name
           
      - name: Get the ORG, API and VER from the Branch name
        run: |
          echo "branch ---> ${{ github.event.pull_request.head.ref }}"
          string=${{ github.event.pull_request.head.ref }}
          remainder=$string
          Xswaggerhub="${remainder%%-*}"; remainder="${remainder#*-}"          
          XORG="${remainder%%-*}"; remainder="${remainder#*-}"
          XAPI="${remainder%%-*}"; remainder="${remainder#*-}"
          XVER="${remainder%%-*}"; remainder="${remainder#*-}"
          echo "ORG=$XORG" >> $GITHUB_ENV 
          echo "API=$XAPI" >> $GITHUB_ENV          
          echo "VER=$XVER" >> $GITHUB_ENV

# run validation checks, that fail with exit 1
#  - un-redsolved comments
#  - critical rule violations
#  - payload Assertion vs. Auto-mock
#  - breaking changes from version 1.0.0

      - name: Prepare scripts for execution
        run: |
          chmod +x ./scripts/cicd_check_comments.sh  
          chmod +x ./scripts/cicd_check_validation.sh 
          chmod +x ./scripts/cicd_get_auto-mock.sh 
          chmod +x ./scripts/breaking_changes.sh
                    
      - name: Check for Open commenets    
        run: ./scripts/cicd_check_comments.sh $ORG $API $VER
  
      - name: Check for Standardization rule violations   
        run: ./scripts/cicd_check_validation.sh $ORG $API $VER
  
      - name: Check for Payload compliance   
        run: ./scripts/cicd_get_auto-mock.sh $ORG $API $VER /$XPATH json ./assertions/$ORG-$API-$VER-$XPATH-get.txt
  
      - name: Check for Breaking changes against 1.0.0   
        run: ./scripts/breaking_changes.sh $ORG $API $VER 1.0.0 y y
                
# if all checks pass:
#  - set the API to published 
#  - saet the API/Version to Defauly
#  - publish documentation to bump.sh

      - name: Publish the API
        run: |
          swaggerhub api:publish "SmartBear_Org/Book/1.1.0"
      
      - name: Set API to default
        run: |
          swaggerhub api:setdefault "SmartBear_Org/Book/1.1.0"
          
      - name: Deploy API documentation to bump.sh
        uses: bump-sh/github-action@0.1
        with:
          id: d3df0e2b-b07e-4bab-8aee-4fc8d6daa54f
          token: 67843a6e628f94b2811231c6454116a7
          file: ./yaml-resolved/swagger.yaml
          
    env:
      HOME: ${{ './scripts' }}
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_KEY }}
      SWAGGERHUB_URL: ${{ 'https://swaggerhub.mwhiggins.com/v1' }}
      NODE_EXTRA_CA_CERTS: ${{ './.ssh/ca_bundle.crt' }}
      XPATH: ${{ 'book' }}
   
