# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: API CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install swaggerhub-cli -g && npm install js-yaml
      - run: sudo apt-get --yes --quiet install jq

# run validation checks, that fail with exit 1
#  - un-redsolved comments
#  - critical rule violations
#  - payload assertions vs. mocks

      - run: chmod +x ./scripts/cicd_check_comments.sh     
      - run: ./scripts/cicd_check_comments.sh $ORG $API $VER
        
      - run: chmod +x ./scripts/cicd_check_validation.sh     
      - run: ./scripts/cicd_check_validation.sh $ORG $API $VER

      - run: chmod +x ./scripts/cicd_get_auto-mock.sh     
      - run: ./scripts/cicd_get_auto-mock.sh $ORG $API $VER /$PATH json ./assertions/$ORG-$API-$VER-$APTH-get.txt
        
# if all checks pass, set the API to published and default

      - run: |
          swaggerhub api:publish "SmartBear_Org/Book/1.1.0"
      - run: |
          swaggerhub api:setdefault "SmartBear_Org/Book/1.1.0"
        
    env:
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_KEY }}
      SWAGGERHUB_URL: ${{ 'https://swaggerhub.mwhiggins.com/v1' }}
      NODE_EXTRA_CA_CERTS: ${{ './.ssh/ca_bundle.crt' }}
      ORG: ${{ 'SmartBear_Org' }}
      API: ${{ 'Book' }}
      VER: ${{ '1.1.0' }}  
      PATH: ${{ 'book' }}
      
