# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: API CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install swaggerhub-cli -g && npm install js-yaml
      - run: sudo apt-get --yes --quiet install jq

# get the ORG, API and VER from the branch name

      - name: Get the ORG, API, VER from the Branch name
        run: |
          work=$GITHUB_BASE_REF
          string=${work##*/}
          remainder=$string
          XXXX="${remainder%%-*}"; remainder="${remainder#*-}"          
          XORG="${remainder%%-*}"; remainder="${remainder#*-}"
          XAPI="${remainder%%-*}"; remainder="${remainder#*-}"
          XVER="${remainder%%-*}"; remainder="${remainder#*-}"         
          echo "ORG=$(echo $XORG >> $GITHUB_ENV)
          echo "API=$(echo $XAPI >> $GITHUB_ENV)          
          echo "VER=$(echo $XVER >> $GITHUB_ENV)  
          echo "the API is: ${{ env.API }}"
          exit 1

# run validation checks, that fail with exit 1
#  - un-redsolved comments
#  - critical rule violations
#  - payload Assertion vs. Auto-mock

      - run: chmod +x ./scripts/cicd_check_comments.sh     
      - run: ./scripts/cicd_check_comments.sh $ORG $API $VER
        
      - run: chmod +x ./scripts/cicd_check_validation.sh     
      - run: ./scripts/cicd_check_validation.sh $ORG $API $VER

      - run: chmod +x ./scripts/cicd_get_auto-mock.sh     
      - run: ./scripts/cicd_get_auto-mock.sh $ORG $API $VER /$XPATH json ./assertions/$ORG-$API-$VER-$XPATH-get.txt
        
# if all checks pass:
#  - set the API to published 
#  - saet the API/Version to Defauly
#  - publish documentation to bump.sh

      - run: |
          swaggerhub api:publish "SmartBear_Org/Book/1.1.0"
      - run: |
          swaggerhub api:setdefault "SmartBear_Org/Book/1.1.0"
          
      - name: Deploy API documentation to bump.sh
        uses: bump-sh/github-action@0.1
        with:
          id: d3df0e2b-b07e-4bab-8aee-4fc8d6daa54f
          token: 67843a6e628f94b2811231c6454116a7
          file: ./yaml-resolved/swagger.yaml
    env:
      HOME: ${{ './scripts' }}
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_KEY }}
      SWAGGERHUB_URL: ${{ 'https://swaggerhub.mwhiggins.com/v1' }}
      NODE_EXTRA_CA_CERTS: ${{ './.ssh/ca_bundle.crt' }}
#      ORG: ${{ 'SmartBear_Org' }}
#      API: ${{ 'Book' }}
#      VER: ${{ '1.1.0' }}  
      XPATH: ${{ 'book' }}
      
